"""add_favorites_table

Revision ID: 75558d6b1fbc
Revises: bb17ac1e73db
Create Date: 2026-03-21 18:20:09.748782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75558d6b1fbc'
down_revision: Union[str, None] = 'bb17ac1e73db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_recipe_favorite')
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('recipe_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'user_id', name='uq_recipe_rating_user')
    )
    op.create_index(op.f('ix_recipe_ratings_recipe_id'), 'recipe_ratings', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_ratings_user_id'), 'recipe_ratings', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'ai_recipe_catalog', ['normalized_name'])
    op.drop_index(op.f('ix_chat_messages_user_created'), table_name='chat_messages')
    op.drop_index(op.f('ix_cooking_days_cooking_streak_id'), table_name='cooking_days')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_fcm_tokens_token'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_festivals_date'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_year'), table_name='festivals')
    op.drop_index(op.f('ix_grocery_items_grocery_list_id'), table_name='grocery_items')
    op.drop_index(op.f('ix_meal_plan_items_meal_plan_id'), table_name='meal_plan_items')
    op.drop_index(op.f('ix_meal_plans_user_active'), table_name='meal_plans')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_nutrition_goals_food_category'), table_name='nutrition_goals')
    op.drop_index(op.f('ix_nutrition_goals_user_id'), table_name='nutrition_goals')
    op.drop_constraint(op.f('uq_nutrition_goals_user_category'), 'nutrition_goals', type_='unique')
    op.alter_column('recipe_ingredients', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'unit',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_instructions_recipe_id'), table_name='recipe_instructions')
    op.drop_index(op.f('ix_recipe_rules_action'), table_name='recipe_rules')
    op.drop_index(op.f('ix_recipe_rules_target_type'), table_name='recipe_rules')
    op.drop_index(op.f('ix_recipe_rules_updated_at'), table_name='recipe_rules')
    op.drop_index(op.f('ix_recipe_rules_user_id'), table_name='recipe_rules')
    op.drop_index(op.f('uq_recipe_rules_dedup'), table_name='recipe_rules')
    op.drop_index(op.f('ix_recipes_is_active'), table_name='recipes')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_usage_logs_action_created'), table_name='usage_logs')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_constraint(op.f('uq_user_achievement'), 'user_achievements', type_='unique')
    op.add_column('users', sa.Column('preferences_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('uq_users_email_lower'), table_name='users', postgresql_where='(email IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=True, postgresql_where='(email IS NOT NULL)')
    op.drop_column('users', 'preferences_updated_at')
    op.create_unique_constraint(op.f('uq_user_achievement'), 'user_achievements', ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_action_created'), 'usage_logs', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_recipes_is_active'), 'recipes', ['is_active'], unique=False)
    op.create_index(op.f('uq_recipe_rules_dedup'), 'recipe_rules', ['user_id', sa.literal_column('upper(target_name::text)'), 'action', 'target_type', sa.literal_column("COALESCE(meal_slot, 'ANY'::character varying)")], unique=True)
    op.create_index(op.f('ix_recipe_rules_user_id'), 'recipe_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_recipe_rules_updated_at'), 'recipe_rules', ['updated_at'], unique=False)
    op.create_index(op.f('ix_recipe_rules_target_type'), 'recipe_rules', ['target_type'], unique=False)
    op.create_index(op.f('ix_recipe_rules_action'), 'recipe_rules', ['action'], unique=False)
    op.create_index(op.f('ix_recipe_instructions_recipe_id'), 'recipe_instructions', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.alter_column('recipe_ingredients', 'unit',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_nutrition_goals_user_category'), 'nutrition_goals', ['user_id', 'food_category'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_nutrition_goals_user_id'), 'nutrition_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_nutrition_goals_food_category'), 'nutrition_goals', ['food_category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_active'), 'meal_plans', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_meal_plan_items_meal_plan_id'), 'meal_plan_items', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_grocery_items_grocery_list_id'), 'grocery_items', ['grocery_list_id'], unique=False)
    op.create_index(op.f('ix_festivals_year'), 'festivals', ['year'], unique=False)
    op.create_index(op.f('ix_festivals_date'), 'festivals', ['date'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_token'), 'fcm_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_cooking_days_cooking_streak_id'), 'cooking_days', ['cooking_streak_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_created'), 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'ai_recipe_catalog', type_='unique')
    op.drop_index(op.f('ix_recipe_ratings_user_id'), table_name='recipe_ratings')
    op.drop_index(op.f('ix_recipe_ratings_recipe_id'), table_name='recipe_ratings')
    op.drop_table('recipe_ratings')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
